### ISSUE TITLE
Unable to access shared link

### ISSUE THREAD

**Issue by FriedaSmith** [SeanNobel/speech-decoding#20]
Hi. Unable to access shared  [link](https://drive.google.com/file/d/1qXyDFHhIKw7e-llEklLh02D6DuSTTqFg/view?usp=sharing) for the merged version of the audio files.

**Comment by SeanNobel** [comment]
Hi,
because we've included merging of audio files inside preprocessing, you won't need it after the next merge to `main`. (FYI, currently `roman_002_1` branch does it)
And sorry, I don't have the merged file anymore.

If you have downloaded `audio.zip` from [here](https://deepblue.lib.umich.edu/data/concern/data_sets/bg257f92t) and unzipped it, here is a code which you can use for merging 12 audio files into a single one.

```python
import torch
import torchaudio
import glob
from natsort import natsorted

audio_paths = natsorted(glob.glob('audio/*.wav'))
audios = [torchaudio.load(path) for path in audio_paths]

# waveform: ( 1, 31908132 )
waveform = torch.cat([a[0] for a in audios], dim=1)
sample_rate = audios[0][1]

torchaudio.save('merged.wav', waveform, sample_rate)
```

**Comment by FriedaSmith** [comment]
Thank you very much indeed!
